steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO_NAME/$_SERVICE_NAME:latest', '-f', 'duracell-ai-agent/Dockerfile', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO_NAME/$_SERVICE_NAME:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO_NAME/$_SERVICE_NAME:latest'
      - '--region'
      - '$_LOCATION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=$_VERTEX_LOCATION,PROXY_HEADER=$_PROXY_HEADER'

images:
  - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO_NAME/$_SERVICE_NAME:latest'

substitutions:
  _LOCATION: europe-west1
  _VERTEX_LOCATION: global
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _AR_REPO_NAME: duracell-repo
  _SERVICE_NAME: duracell-ai-agent
  _PROXY_HEADER: fTRGf93Zq6QyMA9pox6zzQZSrW72ppNZ
